# Generated by Django 2.2.6 on 2019-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
