# Generated by Django 2.2.6 on 2019-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20191011_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
