# Generated by Django 2.2.6 on 2019-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_auto_20191004_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=40),
        ),
    ]
