# Generated by Django 2.2.6 on 2019-10-14 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_tag_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-article_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-tag_date']},
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
