# Generated by Django 2.2.6 on 2019-10-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0013_post_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='image'),
        ),
    ]
