# Generated by Django 2.2.6 on 2019-10-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0014_auto_20191015_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image', verbose_name='image'),
        ),
    ]
