# Generated by Django 2.2.6 on 2019-10-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0015_auto_20191015_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='image'),
        ),
    ]
