# Generated by Django 2.2.6 on 2019-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0016_auto_20191015_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='image'),
        ),
    ]
