# Generated by Django 2.2.6 on 2019-10-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0017_auto_20191015_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article_image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='image'),
        ),
    ]
