# Generated by Django 2.2.6 on 2019-10-15 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_blog', '0018_auto_20191015_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comments', models.TextField()),
                ('date_comments', models.DateTimeField(auto_now_add=True)),
                ('id_comments', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('type_comments', models.ForeignKey(on_delete='CASCADE', to='contenttypes.ContentType')),
            ],
        ),
    ]
