# Generated by Django 2.2.6 on 2019-10-15 18:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0019_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id_comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text_comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='type_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='my_blog.Post', verbose_name='Заметка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
